### ISSUE TITLE
Error when deploying to hardhat network

### ISSUE THREAD

**Issue by DsAtHuH** [moontography/contracts#12]
Following the instructions in README, I've reached an error with wrong argument count in the constructor:

```bash
❯ CONTRACT_NAME=MTGY npx hardhat run --network hardhat scripts/deploy.js
Deploying contracts with the account: 0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266
Account balance: 10000000000000000000000
Error: missing argument:  in Contract constructor (count=0, expectedCount=1, code=MISSING_ARGUMENT, version=contracts/5.4.1)
    at Logger.makeError (/home/dsathuh/Workspaces/HUH/moontography-contracts/node_modules/@ethersproject/logger/src.ts/index.ts:225:28)
    at Logger.throwError (/home/dsathuh/Workspaces/HUH/moontography-contracts/node_modules/@ethersproject/logger/src.ts/index.ts:237:20)
    at Logger.checkArgumentCount (/home/dsathuh/Workspaces/HUH/moontography-contracts/node_modules/@ethersproject/logger/src.ts/index.ts:296:18)
    at ContractFactory.<anonymous> (/home/dsathuh/Workspaces/HUH/moontography-contracts/node_modules/@ethersproject/contracts/src.ts/index.ts:1201:16)
    at step (/home/dsathuh/Workspaces/HUH/moontography-contracts/node_modules/@ethersproject/contracts/lib/index.js:48:23)
    at Object.next (/home/dsathuh/Workspaces/HUH/moontography-contracts/node_modules/@ethersproject/contracts/lib/index.js:29:53)
    at /home/dsathuh/Workspaces/HUH/moontography-contracts/node_modules/@ethersproject/contracts/lib/index.js:23:71
    at new Promise (<anonymous>)
    at __awaiter (/home/dsathuh/Workspaces/HUH/moontography-contracts/node_modules/@ethersproject/contracts/lib/index.js:19:12)
    at ContractFactory.deploy (/home/dsathuh/Workspaces/HUH/moontography-contracts/node_modules/@ethersproject/contracts/lib/index.js:1111:16) {
  reason: 'missing argument:  in Contract constructor',
  code: 'MISSING_ARGUMENT',
  count: 0,
  expectedCount: 1
}
```

**Comment by whatl3y** [comment]
This is a basic hardhat question/issue. I recommend learning how to use hardhat and understanding the solidity compiler before trying to deploy contracts from this repo.

**Comment by DsAtHuH** [comment]
The funny thing is I know how to use hardhat...
